{% set name = "pytest-workflow" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 063338d1387abe286a20fa4a415a66eb945c26a20e947db6117a924d8ed06d48

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  build:
    - pip
    - python >=3.7
    - setuptools
  run:
    - jsonschema
    - pytest >=7.0.0
    - python >=3.7
    - pyyaml

test:
  imports:
    - pytest_workflow

about:
  home: https://github.com/LUMC/pytest-workflow
  license: AGPL-3.0-or-later
  license_family: AGPL
  license_file: LICENSE
  summary: A pytest plugin for configuring workflow/pipeline tests using YAML files
  doc_url: https://pytest-workflow.readthedocs.io

extra:
  recipe-maintainers:
    - rhpvorderman
    - DavyCats
    - Redmar-van-den-Berg
