{% set name = "pytest-workflow" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8fb9fb31a6132c783231afbbbb92941297a42713dcd459694b5efe4a13b8cba7

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - jsonschema
    - pip
    - pytest >=5.4.0
    - python >=3.6
    - pyyaml
    - setuptools
  run:
    - jsonschema
    - pytest >=5.4.0
    - python >=3.6
    - pyyaml

test:
  imports:
    - pytest_workflow

about:
  home: https://github.com/LUMC/pytest-workflow
  license: AGPL-3.0-or-later
  license_family: AGPL
  license_file: LICENSE
  summary: A pytest plugin for configuring workflow/pipeline tests using YAML files
  doc_url: https://pytest-workflow.readthedocs.io

extra:
  recipe-maintainers:
    - rhpvorderman
    - DavyCats
    - Redmar-van-den-Berg
