{% set name = "pytest-workflow" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dc86ad9a5f94482aec14926788f6b78b428be68ee0428cbca22f89b6326f8b7a

build:
  noarch: python
  number: 1
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - jsonschema
    - pytest >=7.0.0
    - python >={{ python_min }}
    - pyyaml
    - xopen >=1.4.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - pytest_workflow

about:
  home: https://github.com/LUMC/pytest-workflow
  license: AGPL-3.0-or-later
  license_family: AGPL
  license_file: LICENSE
  summary: A pytest plugin for configuring workflow/pipeline tests using YAML files
  doc_url: https://pytest-workflow.readthedocs.io

extra:
  recipe-maintainers:
    - rhpvorderman
    - DavyCats
    - Redmar-van-den-Berg
